#!/bin/sh /etc/rc.common                                                
START=99                                                                
USE_PROCD=1                                                             
                                                                        
start_service() {                                                       
    procd_open_instance                                                 
    ip link add ptp0 type veth peer name ptp1                           
    ip link set ptp1 master br-lan                                      
    ip link set ptp0 up                                                 
    ip link set ptp1 up                                                 
    procd_set_param command /usr/sbin/ptp4l -i ptp0 -S -P -m --logSyncIn
    procd_set_param stdout 1                                            
    procd_set_param stderr 1                                            
    procd_set_param respawn                                             
    procd_close_instance                                                
} 